[project]
name = "california-fire-crisis"
version = "0.1.0"
description = "This project analyzes wildfire activity in California using historical fire data. The purpose of the project is to explore trends in wildfire size, frequency, and damage, while demonstrating a clean and reproducible data science workflow."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]
